Ajout des working directories
lebrice/ift6758.github.io pull request #16
Opened 2019-12-13 21:31 UTC by remidion

2019-12-14 04:13 UTC, lebrice commented
Il faut pas que vous rajoutiez les checkpoints dans le commit! Ca rend ça vraiment gros!

2019-12-14 04:13 UTC, lebrice requested changes
Il faut pas que vous rajoutiez les checkpoints dans le commit! Ca rend ça vraiment gros!

2019-12-14 06:50 UTC, remidion commented
J'ai apporté les modifications.  J'ai retiré le data ce qui a libéré pas mal d'espace

2019-12-14 15:16 UTC, IsaVia777 commented
Je pense qu'on peut supprimer tous les checkpoints dans mon directory:
ift6758.github.io/project/workshop/IsabelleWorkshop/model_experiments/checkpoints/
et ne garder que les logs.

2019-12-14 15:57 UTC, MarieStLaurent commented
tu peux tuer x_train.csv!! C'est un .csv de la matrice de features du train
set, je pensais naivement que ca serait plus court à reloader qu'à recréer,
mais c'est tellement gros que ça sert absolument à rien. J'aurais dû
l'effacer.



On Sat, Dec 14, 2019 at 10:16 AM IsaVia777 <notifications@github.com> wrote:

> Je pense qu'on peut supprimer tous les checkpoints dans mon directory:
>
> ift6758.github.io/project/workshop/IsabelleWorkshop/model_experiments/checkpoints/
> et ne garder que les logs.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/lebrice/ift6758.github.io/pull/16?email_source=notifications&email_token=ACHIFZP2TUHUNDI4R2RWECLQYT2GHA5CNFSM4J2WML3KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEG4EY7Y#issuecomment-565726335>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACHIFZNRPUZQIZYUHLHJL4DQYT2GHANCNFSM4J2WML3A>
> .
>

2019-12-15 02:55 UTC, lebrice approved these changes

2019-12-15 19:18 UTC, merged